_wandb:
    value:
        cli_version: 0.25.1
        e:
            z8t1ldwq2dszk56irwsi6xx9y828w95z:
                codePath: train_sb3_sac.py
                codePathLocal: train_sb3_sac.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "499450433536"
                        used: "448752267264"
                email: ejilendragon@gmail.com
                executable: C:\Users\Kessigen\miniconda3\python.exe
                host: DESKTOP-CBOIHIP
                memory:
                    total: "17072005120"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Kessigen\Downloads\widowxv3\train_sb3_sac.py
                python: CPython 3.13.12
                root: C:\Users\Kessigen\Downloads\widowxv3
                startedAt: "2026-04-13T12:23:09.696060Z"
                writerId: z8t1ldwq2dszk56irwsi6xx9y828w95z
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 61
            "4": 3.13.12
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
algorithm:
    value: SAC
batch_size:
    value: 256
buffer_size:
    value: 1000000
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
net_arch:
    value:
        - 256
        - 256
        - 256
tau:
    value: 0.005
total_timesteps:
    value: 500000
